!ArenaConfig
arenas:
  0: !Arena
    t: 0
    rand_all_colors: false
    rand_all_sizes: true
    items:
    - !Item
      name: Beam1
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: Beam2
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: CubeTunnel
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: HalfCylinder
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: InnerWall
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: TransparentWall
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: Cardbox1
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: Cardbox2
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: Cylinder
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: CubeTransparent
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: Tool
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: WoodLog
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: BadGoal
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: DeathZone
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: GoodGoal
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: GoodGoalMulti
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: GoodGoalMulti
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: GoodGoalMulti
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: Tool
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: Ramp
      positions: []
      rand_color: false
      rotations: []
      sizes: []
    - !Item
      name: MazeGenerator
      positions: []
      rand_color: false
      rotations: []
      sizes: []
  1: !Arena
    t: 0
    rand_all_colors: false
    rand_all_sizes: true
    items:
      - !Item
        name: Beam1
        positions: []
        rand_color: false
        rand_size: false
        rotations: []
        sizes: []
      - !Item
        name: Beam2
        positions: []
        rand_color: false
        rand_size: false
        rotations: []
        sizes: []
      - !Item
        name: CubeTunnel
        positions: []
        rand_color: false
        rand_size: false
        rotations: []
        sizes: []
      - !Item
        name: HalfCylinder
        positions: []
        rand_color: false
        rand_size: false
        rotations: []
        sizes: []
      - !Item
        name: InnerWall
        positions: []
        rand_color: false
        rand_size: false
        rotations: []
        sizes: []
      - !Item
        name: TransparentWall
        positions: []
        rand_color: false
        rand_size: false
        rotations: []
        sizes: []
      - !Item
        name: Cardbox1
        positions: []
        rand_color: false
        rand_size: false
        rotations: []
        sizes: []
  2: !Arena
    t: 0
    rand_all_colors: false
    rand_all_sizes: true
    items:
      - !Item
        name: Beam1
        positions: []
        rand_color: false
        rand_size: false
        rotations: []
        sizes: []
      - !Item
        name: Beam2
        positions: []
        rand_color: false
        rand_size: false
        rotations: []
        sizes: []
      - !Item
        name: CubeTunnel
        positions: []
        rand_color: false
        rand_size: false
        rotations: []
        sizes: []
      - !Item
        name: HalfCylinder
        positions: []
        rand_color: false
        rand_size: false
        rotations: []
        sizes: []
      - !Item
        name: InnerWall
        positions: []
        rand_color: false
        rand_size: false
        rotations: []
        sizes: []
      - !Item
        name: TransparentWall
        positions: []
        rand_color: false
        rand_size: false
        rotations: []
        sizes: []
      - !Item
        name: Cardbox1
        positions: []
        rand_color: false
        rand_size: false
        rotations: []
        sizes: []
  3: !Arena
    t: 0
    rand_all_colors: false
    rand_all_sizes: true
    items:
      - !Item
        name: Beam1
        positions: []
        rand_color: false
        rand_size: false
        rotations: []
        sizes: []
      - !Item
        name: Beam2
        positions: []
        rand_color: false
        rand_size: false
        rotations: []
        sizes: []
      - !Item
        name: CubeTunnel
        positions: []
        rand_color: false
        rand_size: false
        rotations: []
        sizes: []
      - !Item
        name: HalfCylinder
        positions: []
        rand_color: false
        rand_size: false
        rotations: []
        sizes: []
      - !Item
        name: InnerWall
        positions: []
        rand_color: false
        rand_size: false
        rotations: []
        sizes: []
      - !Item
        name: TransparentWall
        positions: []
        rand_color: false
        rand_size: false
        rotations: []
        sizes: []
      - !Item
        name: Cardbox1
        positions: []
        rand_color: false
        rand_size: false
        rotations: []
        sizes: []

