!ArenaConfig
arenas:
  0: !Arena
    t: 0
    items:
    - !Item
      name: Cube
      positions:
      - !Vector3 {x: 10, y: 0, z: 10}
      - !Vector3 {x: -1, y: 0, z: 30}
      colors: []
      rotations: [45]
      sizes:
      - !Vector3 {x: -1, y: 5, z: -1}
    - !Item
      name: Cylinder
      positions: []
      colors: []
      rotations: []
      sizes: []
    - !Item
      name: GoodGoal
      positions: []
      colors: []
      rotations: []
      sizes: []