!ArenaConfig
arenas:
  0: !Arena
    t: 0
    items:
    - !Item
      name: GoodGoalBounce
      positions: []
      colors: []
      rotations: []
      sizes: []
    - !Item
      name: BadGoalBounce
      positions: []
      colors: []
      rotations: []
      sizes: []