!ArenaConfig
arenas:
  0: !Arena
    t: 0
    items:
    - !Item
      name: GoodGoal
      positions: []
      colors: []
      rotations: []
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Cube
    - !Item
      name: CubeTransparent
    - !Item
      name: Cardbox1
    - !Item
      name: Cardbox2
    - !Item
      name: WoodLog
    - !Item
      name: UObject
    - !Item
      name: LObject