!ArenaConfig
arenas:
  0: !Arena
    t: 0
    items:
    - !Item
      name: GoodGoal
      positions: []
      colors: []
      rotations: []
      sizes: []
    - !Item
      name: GoodGoal
      positions: []
      colors: []
      rotations: []
      sizes: []
    - !Item
      name: BadGoal
      positions: []
      colors: []
      rotations: []
      sizes: []