!ArenaConfig
arenas:
  0: !Arena
    t: 0
    items:
    - !Item
      name: CubeTunnel
    - !Item
      name: CylinderTunnel
    - !Item
      name: Cylinder
    - !Item
      name: Ramp
    - !Item
      name: Wall
    - !Item
      name: WallTransparent
    - !Item
      name: Cube
    - !Item
      name: CubeTransparent
    - !Item
      name: Cardbox1
    - !Item
      name: Cardbox2
    - !Item
      name: WoodLog
    - !Item
      name: UObject
    - !Item
      name: LObject
    - !Item
      name: GoodGoal
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
    - !Item
      name: GoodGoalMulti
    - !Item
      name: MazeGenerator
    - !Item
      name: GoodGoalMove
    - !Item
      name: GoodGoalBounce
    - !Item
      name: BadGoalMove
    - !Item
      name: BadGoalBounce
    - !Item
      name: GoodGoalMultiMove
    - !Item
      name: GoodGoalMultiBounce
  1: !Arena
    t: 0
    items:
    - !Item
      name: CubeTunnel
    - !Item
      name: Cylinder
    - !Item
      name: CylinderTunnel
    - !Item
      name: Ramp
    - !Item
      name: Wall
    - !Item
      name: WallTransparent
    - !Item
      name: Cube
    - !Item
      name: CubeTransparent
    - !Item
      name: Cardbox1
    - !Item
      name: Cardbox2
    - !Item
      name: WoodLog
    - !Item
      name: UObject
    - !Item
      name: LObject
    - !Item
      name: GoodGoal
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
    - !Item
      name: GoodGoalMulti
    - !Item
      name: GoodGoalMulti
    - !Item
      name: MazeGenerator
  2: !Arena
    t: 0
    items:
    - !Item
      name: CubeTunnel
    - !Item
      name: Cylinder
    - !Item
      name: CylinderTunnel
    - !Item
      name: Ramp
    - !Item
      name: Wall
    - !Item
      name: WallTransparent
    - !Item
      name: Cube
    - !Item
      name: CubeTransparent
    - !Item
      name: Cardbox1
    - !Item
      name: Cardbox2
    - !Item
      name: WoodLog
    - !Item
      name: UObject
    - !Item
      name: LObject
    - !Item
      name: GoodGoal
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
    - !Item
      name: GoodGoalMulti
    - !Item
      name: GoodGoalMulti
    - !Item
      name: MazeGenerator
  3: !Arena
    t: 0
    items:
    - !Item
      name: CubeTunnel
    - !Item
      name: Cylinder
    - !Item
      name: CylinderTunnel
    - !Item
      name: Ramp
    - !Item
      name: Wall
    - !Item
      name: WallTransparent
    - !Item
      name: Cube
    - !Item
      name: CubeTransparent
    - !Item
      name: Cardbox1
    - !Item
      name: Cardbox2
    - !Item
      name: WoodLog
    - !Item
      name: UObject
    - !Item
      name: LObject
    - !Item
      name: GoodGoal
    - !Item
      name: BadGoal
    - !Item
      name: DeathZone
    - !Item
      name: GoodGoalMulti
    - !Item
      name: GoodGoalMulti
    - !Item
      name: MazeGenerator

